### ISSUE TITLE
Error while connecting to Quickbooks

### ISSUE THREAD

**Issue by mmrasheed** [indictranstech/erpnext_quickbooks#21]
Hi,
I am new to ERPNext. I have successfully installed and configured the latest version. However, I am stuck at connecting to Quickbooks using the master branch. I am receiving the following error while trying to connect to Quickbooks-

```
Traceback (most recent call last):
File "/Users/stone/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
response = frappe.handler.handle()
File "/Users/stone/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
execute_cmd(cmd)
File "/Users/stone/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
ret = frappe.call(method, **frappe.form_dict)
File "/Users/stone/frappe-bench/apps/frappe/frappe/__init__.py", line 896, in call
return fn(*args, **newargs)
File "/Users/stone/frappe-bench/apps/erpnext_quickbooks/erpnext_quickbooks/erpnext_quickbooks/doctype/quickbooks_settings/quickbooks_settings.py", line 73, in quickbooks_authentication_popup
quickbooks_settings.authorize_url = quickbooks.get_authorize_url()
File "/Users/stone/frappe-bench/apps/erpnext_quickbooks/erpnext_quickbooks/pyqb/quickbooks/client.py", line 124, in get_authorize_url
params={'oauth_callback': self.callback_url})
File "/Users/stone/frappe-bench/env/lib/python2.7/site-packages/rauth/service.py", line 215, in get_raw_request_token
**kwargs)
File "/Users/stone/frappe-bench/env/lib/python2.7/site-packages/rauth/session.py", line 181, in request
req_kwargs)
File "/Users/stone/frappe-bench/env/lib/python2.7/site-packages/rauth/oauth.py", line 144, in sign
key = self._escape(consumer_secret) + b'&'
File "/Users/stone/frappe-bench/env/lib/python2.7/site-packages/rauth/oauth.py", line 35, in _escape
return quote(self._ensure_unicode(s), safe='~').encode('utf-8')
File "/Users/stone/frappe-bench/env/lib/python2.7/site-packages/rauth/oauth.py", line 25, in _ensure_unicode
return s.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```

Any idea on how to solve this issue? I appreciate your help.

**Comment by jvfiel** [comment]
I have the same problem too. Any updates on this?

**Comment by jk2081** [comment]
Is this being maintained?
