### ISSUE TITLE
Connecting Erpnext to Quickbooks

### ISSUE THREAD

**Issue by priya0wahane** [indictranstech/erpnext_quickbooks#25]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext_quickbooks/erpnext_quickbooks/erpnext_quickbooks/doctype/quickbooks_settings/quickbooks_settings.py", line 73, in quickbooks_authentication_popup
    quickbooks_settings.authorize_url = quickbooks.get_authorize_url()
  File "/home/frappe/frappe-bench/apps/erpnext_quickbooks/erpnext_quickbooks/pyqb/quickbooks/client.py", line 127, in get_authorize_url
    self.request_token = oauth_resp['oauth_token']
KeyError: 'oauth_token'

**Comment by shahrukhas** [comment]
Same error my site

**Comment by shahrukhas** [comment]
Please help me
